<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <SQTRootDir>$(SolutionDir)third_party\sqt\</SQTRootDir>
    <SQTSrcDir>$(SQTRootDir)src</SQTSrcDir>
    <SQTOutDir>$(SQTRootDir)build\out\$(PlatformTarget)\$(Configuration)-MT</SQTOutDir>
  </PropertyGroup>
  <PropertyGroup>
    <IncludePath>$(SQTSrcDir);$(IncludePath)</IncludePath>
    <LibraryPath>$(SQTOutDir);$(LibraryPath)</LibraryPath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <Link>
      <AdditionalDependencies>sqt.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="SQTRootDir">
      <Value>$(SQTRootDir)</Value>
    </BuildMacro>
    <BuildMacro Include="SQTSrcDir">
      <Value>$(SQTSrcDir)</Value>
    </BuildMacro>
    <BuildMacro Include="SQTOutDir">
      <Value>$(SQTOutDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>